Psql setup scripts: Implemented password login. Fixed trigger names to comply with configurator. If trigger exists the script doesnt drop it

diff --git a/reactive-source-psql/src/main/resources/scripts/utils b/reactive-source-psql/src/main/resources/scripts/utils
--- a/reactive-source-psql/src/main/resources/scripts/utils
+++ b/reactive-source-psql/src/main/resources/scripts/utils
@@ -13,7 +13,7 @@ Usage: $0 OPTIONS
 OPTIONS:
    -h host          PSQL server (default localhost)
    -u username      Username (default: $USER)
-   -p password      Password
+   -p password      Password [REQUIRED]
    -P port          Port  number (default: 5432)
    -d database      Database to use in order to connect to the database (default: postgres).
                     Specify only if for some reason you have removed the postgres database
@@ -25,15 +25,30 @@ usage_notifications() {
 usage_connection
 cat << EOF
    -t tableName     the name of the table for which you want to setup the notifications
-   -s streamName    The streamName to which the notifications will be pushed. This
-                    is the same as the string you will use to call LISTEN <streamName>
 EOF
+}
+
+create_pgpass_file() {
+    if [[ -z $SERVER ]] || [[ -z $DATABASE ]] || [[ -z $USERNAME ]] || [[ -z $PORT ]] || [[ -z $PASSWORD ]]
+    then
+        echo "ERROR! Attempted to connect to database with invalid parameters"
+        exit 1
+    fi
+    > ~/.pgpass
+    echo "$SERVER:$PORT:$DATABASE:$USERNAME:$PASSWORD" >> ~/.pgpass
+    chmod 600 ~/.pgpass
+}
+
+delete_pgpass_file() {
+    touch ~/.pgpass
+    rm ~/.pgpass
 }
 
 verifyLastCommand() {
   if [ $? -ne 0 ]
   then
     echo $1
+    delete_pgpass_file
     exit 1
   fi
 }
@@ -51,7 +66,7 @@ readConnectionParams() {
   PORT=5432
   PASSWORD=
 
-  while getopts ���:h:d:u:p:P:t:s:��� OPTION
+  while getopts ":h:d:u:p:P:t:s:" OPTION
   do
        case $OPTION in
            h)
@@ -72,7 +87,7 @@ readConnectionParams() {
        esac
   done
 
-  if [[ -z $SERVER ]] || [[ -z $DATABASE ]] || [[ -z $USERNAME ]] || [[ -z $PORT ]]
+  if [[ -z $SERVER ]] || [[ -z $DATABASE ]] || [[ -z $USERNAME ]] || [[ -z $PORT ]] || [[ -z $PASSWORD ]]
   then
     return 1
   else
@@ -84,23 +99,19 @@ readTableAndStreamParams() {
     # read table and stream name parameters
   local OPTIND
 
-  STREAM_NAME=
   TABLE_NAME=
 
-  while getopts ���:h:d:u:p:P:t:s:��� OPTION
+  while getopts ":h:d:u:p:P:t:s:" OPTION
   do
        case $OPTION in
            t)
                TABLE_NAME=$OPTARG
                ;;
-           s)
-               STREAM_NAME=$OPTARG
-               ;;
        esac
   done
 
   # TABLE_NAME and STREAM_NAME must not be empty
-  if [[ -z $STREAM_NAME ]] || [[ -z $TABLE_NAME ]]
+  if [[ -z $TABLE_NAME ]]
   then
     return 1
   else
